### PR TITLE
Update dependencies libproc, bindgen

### LINKED ISSUE #2: Build failing on my Mac
When I try to build this repository on my Mac now, I get error messages like this:

```
$ cargo b
   Compiling libproc v0.12.0
   Compiling wasi-cap-std-sync v13.0.0
   Compiling wasmtime-wasi v13.0.0
error: failed to run custom build command for `libproc v0.12.0`

Caused by:
  process didn't exit successfully: `/Users/Alex/Documents/GitHub/LiveSplit/asr-debugger/target/debug/build/libproc-1cc21033949d4d98/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"mach_port_options_union_(anonymous_at_/Applications/Xcode_app/Contents/Developer/Platforms/MacOSX_platform/Developer/SDKs/MacOSX_sdk/usr/include/mach/port_h_381_2)" is not a valid Ident', /Users/Alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.67/src/fallback.rs:774:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

I try to run it with the `RUST_BACKTRACE=1` suggestion and get this:

```
$ RUST_BACKTRACE=1 cargo b
   Compiling libproc v0.12.0
error: failed to run custom build command for `libproc v0.12.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/Alex/Documents/GitHub/LiveSplit/asr-debugger/target/debug/build/libproc-1cc21033949d4d98/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at '"mach_port_options_union_(anonymous_at_/Applications/Xcode_app/Contents/Developer/Platforms/MacOSX_platform/Developer/SDKs/MacOSX_sdk/usr/include/mach/port_h_381_2)" is not a valid Ident', /Users/Alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.67/src/fallback.rs:774:9
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
     1: core::panicking::panic_fmt
               at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
     2: proc_macro2::fallback::validate_ident
     3: proc_macro2::fallback::Ident::_new
     4: proc_macro2::fallback::Ident::new
     5: proc_macro2::imp::Ident::new
     6: proc_macro2::Ident::new
     7: bindgen::ir::context::BindgenContext::rust_ident_raw
     8: bindgen::ir::context::BindgenContext::rust_ident
     9: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    10: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    11: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    12: <bindgen::ir::comp::CompInfo as bindgen::codegen::CodeGenerator>::codegen
    13: <bindgen::ir::ty::Type as bindgen::codegen::CodeGenerator>::codegen
    14: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    15: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen::{{closure}}
    16: <bindgen::ir::module::Module as bindgen::codegen::CodeGenerator>::codegen
    17: <bindgen::ir::item::Item as bindgen::codegen::CodeGenerator>::codegen
    18: bindgen::codegen::codegen::{{closure}}
    19: bindgen::ir::context::BindgenContext::gen
    20: bindgen::codegen::codegen
    21: bindgen::Bindings::generate
    22: bindgen::Builder::generate
    23: build_script_build::main
    24: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### LINKED ISSUE #23: New release with libproc_rs version bump
Hi there!

I was recently trying to get py-spy to compile on my laptop. I ran into trouble with `libproc_rs` which didn't seem to want to compile on my system. The original issue was reported [here](https://github.com/benfred/py-spy/issues/596)

It seems that `py-spy` depends on `proc-maps`, and `proc-maps` itself depends on `libproc_rs` [here](https://github.com/rbspy/proc-maps/blob/6d6fcb987fe663a7232b90a4182feb0dfc7c1f4c/src/mac_maps/mod.rs#L146) . `libproc_rs` was [fixed](https://github.com/andrewdavidmackenzie/libproc-rs/pull/103) and a new release just went out [a few hours ago](https://crates.io/crates/libproc). I'd be quite thankful if you could put out a new release for `proc-maps` whenever you had the time to do so.

Thanks!

### PR DESCRIPTION
**Pull request by AlexKnauth**
Updating these dependencies fixes https://github.com/CryZe/asr-debugger/issues/2, a build error that I had similar to https://github.com/rbspy/proc-maps/issues/23

### CODE REVIEW

**Comment by AlexKnauth** [comment]
It looks like the FreeBSD CI builds are failing because they can't get the latest [`bindgen` versions on crates.io](https://crates.io/crates/bindgen/versions). The latest version should be `0.68.1`, released 2023-09-06, but the most recent candidate version mentioned on the CI failures is `0.65.1`, released 2023-04-10.

I don't know whether there's an actual version constraint somewhere or whether it's just pulling from an old crates.io catalog. If it's just an old crates.io catalog, where would it need to be updated?

Edit: in the `.github/workflows/ci.yml` file I see references to a dated cargo `cargo-20230425`, and that matches up with `0.65.1` being the most recent `bindgen` version at the time of 2023-04-25.

**Comment by CryZe** [comment]
You could try changing the date there (it's only a cache key, so it only matters that it's different it seems). It looks like it was the solution to the same problem before: https://github.com/rbspy/proc-maps/commit/8c58272dd03d3d19327837d854a488f81be37309

**Comment by AlexKnauth** [comment]
There was also the test failure on Windows. When I try running that test, it seems to get stuck somewhere in the `while address < sysinfo.lpMaximumApplicationAddress` loop in `get_process_page_ranges` in `src/win_maps.rs`.

When I run it the `address` stays at `0x10000`, leading to an infinite loop. `meminfo.BaseAddress` is also `0x10000`, `meminfo.RegionSize` is `0x7ffd0000`, but then `meminfo.BaseAddress.add(meminfo.RegionSize)` just produces `0x10000` again like it didn't add anything at all.

**Comment by AlexKnauth** [comment]
Looks like `Try changing cache key dates` didn't work, it's still not showing any version of `bindgen` after `0.65.1`, released 2023-04-10.

**Comment by CryZe** [comment]
Seems like there is no issue with a locally generated Cargo.lock, so it's indeed a weird quirk of the CI setup here.

**Comment by acj** [comment]
Thanks for trying the cache workaround. Our FreeBSD vagrant image hasn't been rebuilt in a while, so I'm going to try that and will report back.

**Comment by acj** [comment]
The new FreeBSD images worked [here](https://github.com/acj/proc-maps/actions/runs/6306977629/job/17122942478) with your original commit. Can you rebase your branch onto master and try again?

**Comment by AlexKnauth** [comment]
Okay, I've rebased it onto `master` excluding the `Try changing cache key dates` commit

**Review by acj — APPROVED** [review]
Thanks! I'll try to make a release later today.

**Comment by acj** [comment]
This is in 0.3.2.

**Pull request merged**
